CREATE TABLE IF NOT EXISTS customers (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR NOT NULL,
    email VARCHAR NOT NULL,
    password VARCHAR NOT NULL,
    phoneNumber VARCHAR
);

CREATE TABLE IF NOT EXISTS services (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    idCustomer INT NOT NULL,
    serviceName VARCHAR NOT NULL,
    serviceDescription VARCHAR NOT NULL,
    servicePrice INT NOT NULL,
    CONSTRAINT dk_service_users FOREIGN KEY (idUser) REFERENCES customers(id)
);